### ISSUE TITLE
lesson 2 ndisplay

### ISSUE THREAD

**Issue by sofroniewn** [jni/i2k-skimage-napari#16]
`viewer.ndisplay` doesn't do anything, not needed, isn't part of napari API

![image](https://user-images.githubusercontent.com/6531703/100559458-95bace00-3267-11eb-93a6-8fe1855e022f.png)

**Comment by sofroniewn** [comment]
the previous view_image contains `ndisplay=3` anyway. you could have `viewer.dims.ndisplay=3` in case someone has changed it though in mean time

**Comment by jni** [comment]
yeah `viewer.dims.ndisplay = 3` was the goal, I figured that out later in the game 😂 .
