### ISSUE TITLE
lesson 2 adding points with scale

### ISSUE THREAD

**Issue by sofroniewn** [jni/i2k-skimage-napari#21]
```python
maxima = morphology.local_maxima(transformed)
viewer.add_points(
    np.transpose(np.nonzero(maxima)),
    scale=spacing, # don't forget scale
    name='bad points',
    size=4,
    n_dimensional=True,
)
```

the above works nicely, not the use of `scale`, `n_dimensional=True` all to make 2D rendering look nice too, and the slightly larger size

**Comment by sofroniewn** [comment]
similarly

```python
points = viewer.add_points(
    name='interactive points',
    ndim=3,
    size=4,
    scale=spacing,
    n_dimensional=True
)
```

works well

**Comment by sofroniewn** [comment]
we can also then drop the

```python
# scaled points.data

points.data = np.array(
      [[ 8.7       ,  3.10175426,  7.22127134],
       [ 8.7  ....
```

as that isn't needed anymore points data are always unscaled

**Comment by sofroniewn** [comment]
going through this really makes me feel like having the `scale` on the points layer is the better API then having the data itself be in world coords by default (note you still can if you want, just have `scale=[1, 1, 1]`)

**Comment by sofroniewn** [comment]
note 
```python
marker_locations = points.data / spacing
```

becomes
```python
marker_locations = points.data
```
in the next cell

**Comment by jni** [comment]
> having the scale on the points layer is the better API

I don't think one is better than the other — really depends on the use case! But yes, for interchanging images and points, scaled is better. Good thing that it makes the points addition work well! 😅
