### ISSUE TITLE
lesson 3 - on skipping some dask calls

### ISSUE THREAD

**Issue by sofroniewn** [jni/i2k-skimage-napari#26]
not sure i love this "skipping" first time, will try and see if i have another approach

![image](https://user-images.githubusercontent.com/6531703/100563709-e9331900-3273-11eb-9a97-97f719cf899e.png)

**Comment by jni** [comment]
Agreed, let's not skip it, I just found it an interesting learning journey for me but we can speed up the equivalent journey for the learners. =D

**Comment by sofroniewn** [comment]
from @jni - "we should also add a link to the dask dashboard documentation and add it to the notebook"
