### ISSUE TITLE
io is not defined

### ISSUE THREAD

**Issue by tlambert03** [jni/i2k-skimage-napari#4]
in around the 4th code cell of 2_segmentation_and_regionprops, at `nuclei = io.imread('../images/cells.tif')` ...  `io` is not defined

**Comment by sofroniewn** [comment]
note i needed `import tifffile as io` not `import imageio as io` to get the 3D tiff reading right ...

**Comment by jni** [comment]
LOL It should be `from skimage import io`, but yes, better to change to:

```python
import tifffile
nuclei = tifffile.imread(...)
```
