### ISSUE TITLE
Use np.convolve whole time

### ISSUE THREAD

**Issue by sofroniewn** [jni/i2k-skimage-napari#8]
Can we just use `np.convolve` the whole time, I don't think the added explanation of correlate adds much and will only serve to confuse (i didn't appreciate this before looking at example). We can add a `-` sign to the kernel if we want

![image](https://user-images.githubusercontent.com/6531703/100556975-c8aa9500-325a-11eb-8dba-febca632caa8.png)

**Comment by sofroniewn** [comment]
similarly i'd rather use `ndi.convolve` here too

![image](https://user-images.githubusercontent.com/6531703/100557183-386d4f80-325c-11eb-8416-4e960185731e.png)

**Comment by sofroniewn** [comment]
but I guess we are using correlate quite a lot so maybe it's ok ....

![image](https://user-images.githubusercontent.com/6531703/100557329-4ec7db00-325d-11eb-8fc4-03aa1202c19d.png)

**Comment by jni** [comment]
@sofroniewn as discussed in the call I think this is kinda sorta necessary. let's leave it for now.
