### ISSUE TITLE
convolution commutative

### ISSUE THREAD

**Issue by sofroniewn** [jni/i2k-skimage-napari#9]
```
Actually, it turns out that we can do it in any order (convolution is `associative`), so we can create a filter that combines both the difference and the mean.
```

I think you want `commutative` above instead of `associative`, both are true, but [commutativity](https://en.wikipedia.org/wiki/Convolution#Properties) is the relevant one here

**Comment by jni** [comment]
it's not? We demonstrate `((image * smoothkernel) * edgekernel)` vs `(image * (smoothkernel * edgekernel))`?

**Comment by sofroniewn** [comment]
ah nice, ok that's fine - will close
